// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneContacts.Models;

#nullable disable

namespace PhoneContacts.Migrations
{
    [DbContext(typeof(PhoneContext))]
    [Migration("20260909224055_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhoneContacts.Models.Phone", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "123 Main St, Des Moines, IA",
                            Name = "Allie Johnson",
                            Note = "Work Friend",
                            PhoneNumber = "515-555-1234"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "123 Cheddar St, Grimes, IA",
                            Name = "Joe Smiles",
                            Note = "School Friend",
                            PhoneNumber = "515-555-4321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
